# this is the default cloudbuild triggered on push to any github branch
# it simply tests whether the project still builds
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sami-app-base-img", "."]
images:
  - "gcr.io/$PROJECT_ID/sami-app-base-img"
