# this builds our custom Dockerfile so that it can be used within scripts
# the tag field gives it a name that can be accessed
# it is run on every code commit
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sami-app-base-img", "."]
images:
  - "gcr.io/$PROJECT_ID/sami-app-base-img"
