# Use the custom image to install any updates to dependencies, build, test and deploy

steps:
  # Install
  #- name: "gcr.io/cloud-builders/npm"
  #  args: ["install"]
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: yarn
    args: ["install"]
  # Build
  #- name: "gcr.io/cloud-builders/npm"
  #  args: ["run", "build"]
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: npm
    args: ["run", "build"]
  # Test
  #- name: "gcr.io/cloud-builders/npm"
  #  args: ["run", "test:ci"]
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: npm
    args: ["run", "test:ci"]
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "dev"]
