# Use the custom image to install any updates to dependencies, build, test and deploy

steps:
  # Install
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: yarn
    args: ["install"]
    dir: "/app"
  # Build
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: npm
    args: ["run", "build"]
    dir: "/app"
  # Test
  - name: "gcr.io/$PROJECT_ID/sami-app-base-img"
    entrypoint: npm
    args: ["run", "test:ci"]
    dir: "/app"
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "dev"]
