steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build:prod"]
  # Assume tests passed from dev
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "prod"]
